services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  Digilue\SecureDownloadsViewhelper\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  # Service muss public sein f√ºr GeneralUtility::makeInstance() in ViewHelpern
  Digilue\SecureDownloadsViewhelper\Service\SecureDownloadLinkService:
    public: true
